swagger: "2.0"
info:
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.0"
  title: "Bank Argent API documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1"
tags:
- name: "User transactions module"
schemes:
- "http"


paths:
  /user/profile/transactions:
    post:
      security:
        - Bearer: []
      tags:
        - "User transactions module"
      summary: "See all transactions for the current month"
      description: "API for fetching all the transactions of a user in a given time."
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Start and end date for fetched transactions"
          required: true
          schema:
            $ref: '#/definitions/GetTransactionsParameters'
      responses:
        200: 
          description: "Successful operation"
          schema:
            $ref: '#/definitions/TransactionsResponse'
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: "Internal server error"
          schema:
            $ref: '#/definitions/ErrorModel'
          
          
  /user/profile/transaction:
    post:
      security:
          - Bearer: []
      tags:
        - "User transactions module"
      summary: "Check details of a single transaction"
      description: "API for fetching details of a single transaction."
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Id of transaction to fetch"
          required: true
          schema:
            $ref: '#/definitions/GetTransactionParameters'
      responses:
        200: 
          description: "Successful operation"
          schema:
            $ref: '#/definitions/TransactionResponse'
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: "Internal server error"
          schema:
            $ref: '#/definitions/ErrorModel'
    
    put:
      security:
          - Bearer: []
      tags:
        - "User transactions module"
      summary: "Modify informations of a single transaction"
      description: "API to update data of a transaction"
      operationId: "createUsersWithListInput"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Data to update in a transaction"
          required: true
          schema:
            $ref: '#/definitions/UpdateTransactionParameters'
      responses:
        200: 
          description: "Successful operation"
          schema:
            $ref: '#/definitions/TransactionResponse'
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: '#/definitions/ErrorModel'
        500:
          description: "Internal server error"
          schema:
            $ref: '#/definitions/ErrorModel'


securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    

definitions:
  GetTransactionsParameters:
    type: "object"
    properties:
      startDate:
        type: "string"
      endDate:
        type: "string"
        
  GetTransactionParameters:
    type: "object"
    properties:
      id:
        type: "string"
        
  UpdateTransactionParameters:
    type: "object"
    properties:
      id:
        type: "string"
      category:
        type: "string"
      notes:
        type: "string"
  
  TransactionModel:
    type: "object"
    properties:
      id:
        type: "string"
      date:
        type: "string"
      description:
        type: "string"
      amount:
        type: "string"
      balance:
        type: "string"
      transactionType:
        type: "string"
      category:
        type: "string"
      notes:
        type: "string"
        
  TransactionsResponse:
    type: "object"
    properties:
      status:
        type: "number"
      errArg:
        type: "string"
      transactions:
        type: "array"
        items:
          $ref: "#/definitions/TransactionModel"
        
  TransactionResponse:
    type: "object"
    properties:
      status:
        type: "number"
      errArg:
        type: "string"
      transaction:
        type: "object"
        properties:
          id:
            type: "string"
          date:
            type: "string"
          description:
            type: "string"
          amount:
            type: "string"
          balance:
            type: "string"
          transactionType:
            type: "string"
          category:
            type: "string"
          notes:
            type: "string"
            
  ErrorModel:
    type: "object"
    properties:
      status:
        type: "number"
      errArg:
        type: "string"
