swagger: "2.0"
info:
  description: "Contains all available API endpoints in this codebase"
  version: "1.0.0"
  title: "Bank Argent API documentation"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1"
tags:
  - name: "User transactions module"
schemes:
  - "http"

paths:
  /user/account/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - "User transactions module"
      summary: "See all transactions for the current month"
      description: "API for fetching all the transactions of a user in a given time."
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "accountId"
          description: "Id of the account of the user"
          required: true
          type: "string"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/TransactionsResponse"
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: "#/definitions/ErrorModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorModel"

  /user/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - "User transactions module"
      summary: "Check details of a single transaction"
      description: "API for fetching details of a single transaction."
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "Id of the transaction we want to fetch"
          required: true
          type: "string"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/TransactionResponse"
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: "#/definitions/ErrorModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorModel"

    patch:
      security:
        - Bearer: []
      tags:
        - "User transactions module"
      summary: "Modify informations of a single transaction"
      description: "API to update data of a transaction"
      operationId: "createUsersWithListInput"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "transactionId"
          description: "Id of the transaction we want to edit"
          required: true
          type: "string"
        - in: "header"
          name: "Authorization"
          description: "Attach Bearer JWT token"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Data to update in a transaction"
          required: true
          schema:
            $ref: "#/definitions/UpdateTransactionParameters"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/TransactionResponse"
        400:
          description: "Invalid data sent to API"
          schema:
            $ref: "#/definitions/ErrorModel"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/ErrorModel"

securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"

definitions:
  UpdateTransactionParameters:
    type: "object"
    properties:
      category:
        type: "string"
      notes:
        type: "string"

  TransactionModel:
    type: "object"
    properties:
      id:
        type: "string"
      date:
        type: "string"
      description:
        type: "string"
      amount:
        type: "string"
      balance:
        type: "string"
      transactionType:
        type: "string"
      category:
        type: "string"
      notes:
        type: "string"

  TransactionsResponse:
    type: "object"
    properties:
      status:
        type: "number"
      transactions:
        type: "array"
        items:
          $ref: "#/definitions/TransactionModel"

  TransactionResponse:
    type: "object"
    properties:
      status:
        type: "number"
      transaction:
        type: "object"
        properties:
          id:
            type: "string"
          date:
            type: "string"
          description:
            type: "string"
          amount:
            type: "string"
          balance:
            type: "string"
          transactionType:
            type: "string"
          category:
            type: "string"
          notes:
            type: "string"

  ErrorModel:
    type: "object"
    properties:
      status:
        type: "number"
      errArg:
        type: "string"
